language: node_js
node_js:
- '10'
install:
- yarn
script:
- yarn build
- git add .
- git commit -m 'release:github pages'
- git config --local user.name "haitaodesign"
- git config --local user.email "15393243613@163.com"
- git push -f https://${GITHUB_TOKEN}@github.com/haitaodesign/learning-resource.git master
branches:
  only:
  - master