language: node_js
node_js:
- '10'
install:
- yarn
script:
- yarn build
branches:
  only:
  - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
dd:
  secure: g1EEwxJzA0DcSNK42ICEJPoYRKlo3cJtVysiOPkvVeVE/EgqTVxISCKy0sOQnYy6LtpGlY2vUxJ4RqPgu8I1L/1Up+e5GbCF1UvrQp2qEBsM4KB/H0NfT/qPfkkLVho/7ZqXpS3AMNWakOaPLKseFhcEBF1wU1ngW13MrX4hR5deWQE9e2c0THq19KxAM5FZNDS/HD+9z0khuOd+F9CVLFAUgnxlgi5l2zf47ox2r3hVKcHuoLIIBWnlsLZ3W6pYukl53hJsqnm2VtcBX3G27RftEVF3jFNK9k6FQF98hKM22nmDGXLHn/yvPxy13kvOJ9aQcqsn4AcC+Njc4/YaK594quVpYF1V8JjSXLYCwKT0QUv/xmF763gsqdlmNrsmN/a+IR07QQcPs8o7UqKjmsgYQH9+vGGPYxmShscwSYEtysSjwnDUju8lMx8C41TAgQtVlvIs4sc4w9zayld3b+OVVlBybFIB3wzWwJPpySf7+hN+tJ8e5FN/ngraWR3JgbAUxrvR27HS2lfR4Pl5fdJfOJCIGsyF2LGNsk37GL+rj4Oo2Po7Meuq4dWF6BsUArCjRp/NIhajp7rfbm3dbkSUdfaswE582dk3tFQcVXzK4SDeTYD3HoQm5L3DJIEyK0ksgr9gpD+AdshD1iyjFgXdre59ozN/ceUz2youXFE=
